language: cpp
cache: ccache
matrix:
  include:
  - name: OpenCL macOS
    os: osx
    addons:
      homebrew:
        update: true
        packages:
        - bison
        - ccache
        - ceres-solver
        - CMake
        - doxygen
        - faac
        - faad2
        - ffmpeg
        - glew
        - glfw
        - glm
        - jpeg
        - libpng
        - libtiff
        - ninja
        - opencv@3
        - qt
        - yasm
    before_install:
    - export PATH="/usr/local/opt/bison/bin:/usr/local/opt/ccache/libexec:${PATH}"
    script:
    - mkdir build
    - cd build
    - cmake -DCREATE_BOX_PACKAGE=OFF -DGPU_BACKEND_CUDA=OFF -DGPU_BACKEND_OPENCL=ON
      -DMACPORTS=OFF -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5 -G Ninja ..
    - ninja
    deploy:
      provider: s3
      edge: true
      access_key_id: AKIAI2SLK76O6MKJF43Q
      secret_access_key: $AWS_SECRET_KEY
      bucket: hh-builds
      skip_cleanup: true
      on:
        repo: retani/stitchEm
        branch: w-m/mac-package
    
